server:
  port: 8090

spring:
  application:
    name: "glf-communities"
  profiles:
    active: "@spring.profiles.active@"

management:
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"