server:
  port: 8090

spring:
  application:
    name: glf-communities

  config:
    import:
      - "configserver:http://localhost:8071/"
      - "classpath:buildInfo.yml"
      - "classpath:buildEnvInfo.yml"

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"