server:
  port: 8090

spring:
  application:
    name: glf-communities

  config:
    import:
      - "configserver:http://configserver:8071/"
      - "classpath:buildInfo.yml"
      - "classpath:buildEnvInfo.yml"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - busrefresh